import React, { forwardRef } from 'react';
import Bridge from './Bridge';
import Pulse from './Pulse';
import Coil from './Coil';
import Mosfet from './Mosfet';
import Thermistor from './Thermistor';
import CurrentSensor from './CurrentSensor';

export default forwardRef((props, ref) => {
  const path = process.env.REACT_APP_HTTP_PATH;
  const http = `${process.env.REACT_APP_HTTP_PROTOCOL}://${process.env.REACT_APP_HTTP_HOST}:${process.env.REACT_APP_HTTP_PORT}${path}`;
  const assets = `${process.env.REACT_APP_ASSETS_PROTOCOL}://${process.env.REACT_APP_ASSETS_HOST}:${process.env.REACT_APP_ASSETS_PORT}`;
  const engine = `${process.env.REACT_APP_ENGINE_PROTOCOL}://${process.env.REACT_APP_ENGINE_HOST}:${process.env.REACT_APP_ENGINE_PORT}`;
  return (
    <g ref={ref} id="circuit1" className="circuit svg-passive" {...props}>
      <g className="mosfet-pwm">
        <circle cx="0" cy="10" r="1" className="dot" />
        <path d="m 0,10 h 5" />
        <Pulse x="5" y="10" major={false} id="pulse-minor.circuit1" />
      </g>
      <Mosfet
        x="15"
        y="5"
        title="Mosfet #1"
        paragraph="Amplify 5V to 24V PWM signal."
        img={`${assets}/images/IRFZ44N-NChannel-Mosfet.webp`}
        link={`${http}/about#electronics-mosfet`}
      />
      <g className="coil-pwm">
        <Pulse x="55" y="0" major={true} id="pulse-major.circuit1" />
        <Coil
          x="65"
          y="0"
          title="12V Solenoid #1"
          paragraph="Powered by 24V PWM signal."
          img={`${assets}/images/DC-12V-5N-10mm-PushPull-Solenoid.webp`}
          link={`${http}/about#electronics-coil`}
        />
        <circle cx="150" cy="0" r="1" className="dot" />
      </g>
      <g className="supply-24v-bus-horizontal">
        <circle cx="150" cy="0" r="1" />
        <path d="m 140,10 h 10" />
      </g>
      <g className="supply-24v-bus-vertical">
        <circle cx="150" cy="10" r="1" className="dot" />

        <Bridge x="140" y="25" r="90" />
        <path d="m 140,10 v 15" />
        <path d="m 140,35 v 5" />

        <Bridge x="140" y="55" r="90" />
        <path d="m 140,40 v 15" />
        <path d="m 140,65 v 5" />

        <Bridge x="140" y="85" r="90" />
        <path d="m 140,70 v 15" />
        <path d="m 140,95 v 5" />

        <Bridge x="140" y="115" r="90" />
        <path d="m 140,100 v 15" />
        <path d="m 140,125 v 5" />

        <Bridge x="140" y="145" r="90" />
        <path d="m 140,130 v 15" />
        <path d="m 140,155 v 5" />

        <path d="m 140,160 v 30" />
      </g>
      <CurrentSensor
        x="150"
        y="0"
        title="Power Sensor #1"
        paragraph="Monitor power consumed by coil."
        img={`${assets}/images/GY-INA219-I2C-Digital-Current-Sensor.webp`}
        link={`${http}/about#electronics-current`}
      />
      <g className="current-sensor-bus-horizontal">
        <path d="m 200,10 h 10" />
      </g>
      <g className="current-sensor-bus-vertical">
        <circle cx="200" cy="10" r="1" className="dot" />
        <path d="m 210,10 v 30" />

        <circle cx="210" cy="40" r="1" className="dot" />
        <path d="m 210,40 v 30" />

        <circle cx="210" cy="70" r="1" className="dot" />
        <path d="m 210,70 v 30" />

        <circle cx="210" cy="100" r="1" className="dot" />
        <path d="m 210,100 v 30" />

        <circle cx="210" cy="130" r="1" className="dot" />
        <path d="m 210,130 v 30" />

        <circle cx="210" cy="160" r="1" className="dot" />
        <path d="m 210,160 v 30" />
      </g>
      <Thermistor
        x="97.5"
        y="10"
        id="thermistor.circuit1"
        title="Thermistor #1"
        paragraph="Monitor temperature generated by coil."
        img={`${assets}/images/NTC-MK2a-1percent-Thermistor.webp`}
        link={`${http}/about#electronics-thermistor`}
      />
      <g className="thermistor-bus-horizontal">
        <path d="m 112,10 h 18" />
        <path d="m 130,10 v 15" />
        <Bridge x="130" y="25" r="90" />
        <path d="m 130,35 v 5" />
      </g>
      <g className="thermistor-bus-vertical">
        <path d="m 130,40 v 15" />
        <Bridge x="130" y="55" r="90" />
        <path d="m 130,65 v 5" />

        <path d="m 130,70 v 15" />
        <Bridge x="130" y="85" r="90" />
        <path d="m 130,95 v 5" />

        <path d="m 130,100 v 15" />
        <Bridge x="130" y="115" r="90" />
        <path d="m 130,125 v 5" />

        <path d="m 130,130 v 15" />
        <Bridge x="130" y="145" r="90" />
        <path d="m 130,155 v 5" />

        <path d="m 130,160 v 30" />
      </g>
      <g className="supply-5v-bus-horizontal">
        <path d="m 80,10 h 17" />
      </g>
      <g className="supply-5v-bus-vertical">
        <path d="m 80,10 v 15" />
        <Bridge x="80" y="25" r="90" />
        <path d="m 80,35 v 5" />

        <path d="m 80,40 v 15" />
        <Bridge x="80" y="55" r="90" />
        <path d="m 80,65 v 5" />

        <path d="m 80,70 v 15" />
        <Bridge x="80" y="85" r="90" />
        <path d="m 80,95 v 5" />

        <path d="m 80,100 v 15" />
        <Bridge x="80" y="115" r="90" />
        <path d="m 80,125 v 5" />

        <path d="m 80,130 v 15" />
        <Bridge x="80" y="145" r="90" />
        <path d="m 80,155 v 5" />

        <path d="m 80,160 v 30" />
      </g>
      <g className="supply-common-bus">
        <path d="m 70,10 v 15" />
        <Bridge x="70" y="25" r="90" />
        <path d="m 70,35 v 5" />

        <path d="m 70,40 v 15" />
        <Bridge x="70" y="55" r="90" />
        <path d="m 70,65 v 5" />

        <path d="m 70,70 v 15" />
        <Bridge x="70" y="85" r="90" />
        <path d="m 70,95 v 5" />

        <path d="m 70,100 v 15" />
        <Bridge x="70" y="115" r="90" />
        <path d="m 70,125 v 5" />

        <path d="m 70,130 v 15" />
        <Bridge x="70" y="145" r="90" />
        <path d="m 70,155 v 5" />

        <path d="m 70,160 v 30" />
      </g>
    </g>
  );
});
