import React, { forwardRef } from 'react';
import Pulse from './Pulse';
import Coil from './Coil';
import Mosfet from './Mosfet';
import Thermistor from './Thermistor';
import CurrentSensor from './CurrentSensor';

export default forwardRef((props, ref) => {
  const path = process.env.REACT_APP_HTTP_PATH;
  const http = `${process.env.REACT_APP_HTTP_PROTOCOL}://${process.env.REACT_APP_HTTP_HOST}:${process.env.REACT_APP_HTTP_PORT}${path}`;
  const assets = `${process.env.REACT_APP_ASSETS_PROTOCOL}://${process.env.REACT_APP_ASSETS_HOST}:${process.env.REACT_APP_ASSETS_PORT}`;
  const engine = `${process.env.REACT_APP_ENGINE_PROTOCOL}://${process.env.REACT_APP_ENGINE_HOST}:${process.env.REACT_APP_ENGINE_PORT}`;
  return (
    <g ref={ref} id="circuit5" className="circuit svg-passive" {...props}>
      <g className="mosfet-pwm">
        <circle cx="0" cy="160" r="1" className="dot" />
        <path d="m 0,160 h 5" />
        <Pulse x="5" y="160" major={false} id="pulse-minor.circuit5" />
      </g>
      <Mosfet
        x="15"
        y="155"
        title="Mosfet #6"
        paragraph="Amplify 5V to 24V PWM signal.                   "
        img={`${assets}/images/IRFZ44N-NChannel-Mosfet.webp`}
        link={`${http}/about#electronics-mosfet`}
      />
      <g className="coil-pwm">
        <Pulse x="55" y="150" major={true} id="pulse-major.circuit5" />
        <Coil
          x="65"
          y="150"
          title="12V Solenoid #6"
          paragraph="Powered by 24V PWM signal."
          img={`${assets}/images/DC-12V-5N-10mm-PushPull-Solenoid.webp`}
          link={`${http}/about#electronics-coil`}
        />
        <circle cx="150" cy="150" r="1" className="dot" />
      </g>
      <g className="supply-24v-bus-horizontal">
        <circle cx="140" cy="160" r="1" className={'dot'} />
        <circle cx="150" cy="150" r="1" />
        <path d="m 140,160 h 10" />
      </g>
      <g className="supply-24v-bus-vertical">
        <circle cx="150" cy="160" r="1" className="dot" />
        <path d="m 140,160 v 30" />
      </g>
      <CurrentSensor
        x="150"
        y="150"
        title="Power Sensor #6"
        paragraph="Monitor power consumed by coil."
        img={`${assets}/images/GY-INA219-I2C-Digital-Current-Sensor.webp`}
        link={`${http}/about#electronics-current`}
      />
      <g className="current-sensor-bus-horizontal">
        <path d="m 200,160 h 10" />
      </g>
      <g className="current-sensor-bus-vertical">
        <circle cx="200" cy="160" r="1" className="dot" />

        <path d="m 210,160 v 30" />
        <circle cx="210" cy="160" r="1" className="dot" />
      </g>
      <Thermistor
        x="97.5"
        y="160"
        id="thermistor.circuit5"
        title="Thermistor #6"
        paragraph="Monitor temperature generated by coil."
        img={`${assets}/images/NTC-MK2a-1percent-Thermistor.webp`}
        link={`${http}/about#electronics-thermistor`}
      />
      <g className="thermistor-bus-horizontal">
        <path d="m 112,160 h 8" />
        <path d="m 120,160 v 30" />
      </g>
      <g className="supply-5v-bus-horizontal">
        <path d="m 80,160 h 17" />
      </g>
      <g className="supply-5v-bus-vertical">
        <circle cx="80" cy="160" r="1" />
        <path d="m 80,160 v 30" />
      </g>
      <g className="supply-common-bus">
        <circle cx="70" cy="160" r="1" />
        <path d="m 70,160 v 30" />
      </g>
    </g>
  );
});
